# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Christina Kunze – Übersetzungen Ungarisch-Deutsch
description: >- # this means to ignore newlines until "baseurl:"
  Staatlich geprüfte Übersetzerin für Ungarisch und allgemein beeidigte
  Dolmetscherin für die Berliner Gerichte und Notare.
  Sie brauchen eine Übersetzung aus dem Ungarischen?
  Gern übernehme ich Ihren Auftrag.
baseurl: ""
url: "https://rixx.github.io"

nav_de:
  - title: Startseite
    url: /
  - title: Leistungen
    url: /leistungen
  - title: Über mich
    url: /cv
  - title: Übersetzungen
    url: /publikationen
  - title: Links
    url: /links
  - title: [magyar]
    url: /hu

nav_hu:
  - title: Kezdőlap
    url: /hu
  - title: Szolgáltatások
    url: /szolgaltatasok
  - title: Életpálya
    url: /eletpalya
  - title: Fordítások
    url: /forditasok
  - title: Linkek
    url: /links
  - title: [Deutsch]
    url: /
